// Newest work first. Covers are the top of each design at full width.
export const PROJECTS = [
  { title: "JOE MCDAVID", role: "Landing page design", year: "", desc: "A portfolio for a landscape and travel photographer. Oversized editorial type, a strict black and white grid, and plenty of room for the photos to breathe.", tags: ["Figma", "Editorial", "Photography"], cover: 'assets/images/project-joe-mcdavid.jpg' },
  { title: "MAPALO", role: "Landing page design", year: "", desc: "An AI memory product with a hand-drawn identity. Chalky scribble illustrations and a serif wordmark make a technical product feel calm and human.", tags: ["Figma", "Illustration", "AI Product"], cover: 'assets/images/project-mapalo.jpg' },
  { title: "LUMNOS", role: "Landing page design", year: "", desc: "A design studio site built on heavy condensed type and a single gold accent, with a scattered gallery of recent work that rewards scrolling.", tags: ["Figma", "Studio", "Typography"], cover: 'assets/images/project-lumnos.jpg' },
  { title: "GENRETRADE", role: "Landing page design", year: "", desc: "A waitlist page for a platform that turns music genres into tradable assets. Vinyl photography, a lime accent, and an expandable feature list.", tags: ["Figma", "Fintech", "Waitlist"], cover: 'assets/images/project-genretrade.jpg' },
  { title: "INDESIGN", role: "Landing page design", year: "", desc: "A bridal fashion storefront with elegant serif headlines, arched photo crops, and small image pills set right into the copy.", tags: ["Figma", "E-commerce", "Fashion"], cover: 'assets/images/project-indesign.jpg' },
  { title: "ACURA", role: "Landing page design", year: "", desc: "A Dutch real estate site with a search bar over the hero, handpicked listings, a category grid, and an FAQ.", tags: ["Figma", "Real Estate", "Search"], cover: 'assets/images/project-acura.jpg' },
  { title: "JOSHUA EDWARDS", role: "Client website", year: "", desc: "A personal site for a math tutor: his name set huge, one strong photo, reviews from students, and oversized contact links that are impossible to miss.", tags: ["Figma", "Client", "Personal Brand"], cover: 'assets/images/project-joshua-edwards.jpg' },
  { title: "COLLISEAM", role: "Lead Designer and Project Manager", year: "2024\u20132025", desc: "A community platform for junior developers and designers. I led a team of 7 and built the full design system in Figma, from the landing page to the app.", tags: ["Figma", "Design System", "Team of 7"], cover: 'assets/images/project-colliseam.jpg' }
];
